Part1
hilberturi/PFMCPP_Project6 pull request #1
Opened 2023-02-04 09:44 UTC by hilberturi

2023-02-04 17:14 UTC, matkatmusic requested changes
There are several duplicate return statements, which means the logic used in the code can be improved.

2023-02-04 17:14 UTC, matkatmusic commented on main.cpp
>          return nullptr;
D.R.Y.
you have 2 identical return statements.
- [ ] revise the logic

2023-02-04 17:14 UTC, matkatmusic commented on main.cpp
> +        }
- [ ] revise the logic: identical return statements used

2023-02-04 17:14 UTC, matkatmusic commented on main.cpp
> +        return that->adjustedValue * that->exactTargetValue;
- [ ] revise the logic: identical return statements used

2023-02-04 17:14 UTC, matkatmusic commented on main.cpp
> +        std::cout << "'f.compare()' returned nullptr (one arg is nullptr, or both args have same value)"
`one arg is nullptr` is not 100% correct.
- [ ] revise

2023-02-04 17:30 UTC, hilberturi commented on main.cpp
> +        std::cout << "'f.compare()' returned nullptr (one arg is nullptr, or both args have same value)"
yes both args can also be nullptrs

2023-02-05 04:49 UTC, matkatmusic approved these changes

2023-02-05 04:49 UTC, merged